baseurl: "https://www.midwestwomensretreat.com"
title: "Midwest Women's Retreat"
canonifyurls: true
theme: "hugo-conference"

#GoogleAnalytics: ""

params:
  # Conference info
  Name: "Midwest Women's Retreat"
  Description: "3-day Women's Health and Healing Retreat"
  Date: "Friday, June 28 - Sunday June 30, 2019"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "King Conference Center"
  Address: "6404 Woodland Ave"
  City:  "Kansas City"
  State: "Missouri"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyCsd0a6D0gy4ml7sEMzAqSvJFyXVgugFNI"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - tickets
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    tickets: "Tickets"
#    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "#tickets"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/pic.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/pic.png"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/pic.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Check-in"
      time: "Friday - 4:00 pm to 7:00 pm"

    - name: "Meet and Greet"
      time: "Friday - 6:30 pm to 7:00 pm"

    - name: "Taco Dinner"
      time: "Friday - 7:00 pm to 8:00 pm"

    - name: "Yoga Sleep Activity"
      time: "Friday - 8:30 pm"

    - name: "Free Time"
      time: "Friday - 9:15 pm"

    - name: "Yoga and Exercising"
      time: "Saturday - 6:00 am - 7:00 am"

    - name: "Meditation"
      time: "Saturday - 7:30 am - 8:00 am"

    - name: "Breakfast"
      time: "Saturday - 8:00 am - 8:45 am"

    - name: "First Session - Dawn A. Ross"
      time: "Saturday - 9:00 am - 10:30 am"

    - name: "Break"
      time: "Saturday - 10:30 am - 10:45 am"

    - name: "Session 1A or Session 1B"
      time: "Saturday - 10:45 am - 11:45 am"

    - name: "Lunch"
      time: "Saturday - 11:45 am - 12:45 pm"

    - name: "Dr. Whoever"
      time: "Saturday - 1:00 pm - 2:00 pm"

    - name: "Break"
      time: "Saturday - 2:00 pm - 2:15 pm"

    - name: "Session 2A or Session 2B"
      time: "Saturday - 2:15 pm - 3:15 pm"

    - name: "Break"
      time: "Saturday - 3:15 pm - 3:30 pm"

    - name: "Dr. Dawn A. Rodd"
      time: "Saturday - 3:30 pm - 5:00 pm"

    - name: "Dinner"
      time: "Saturday - 6:00 pm"

    - name: "Disco Night"
      time: "Saturday - 8:00 pm"

    - name: "Yoga and Exercising"
      time: "Sunday - 6:00 am - 7:00 am"

    - name: "Meditation"
      time: "Sunday - 7:30 am - 8:00 am"

    - name: "Breakfast"
      time: "Sunday - 8:00 am - 8:45 am"

    - name: "Barbara Courtney"
      time: "Sunday - 9:00 am - 10:30 am"

    - name: "Checkout"
      time: "By Sunday 11:00 am"
